In [46]:
import scipy.io as sio
import numpy as np

In [48]:
dataFilename='my_cancer_dataset.mat'

In [49]:
data=sio.loadmat(dataFilename)

In [50]:
data

{'__header__': b'MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Wed Mar  2 09:53:22 2022',
 '__version__': '1.0',
 '__globals__': [],
 'cancerInputs': array([[0.2, 0.2, 0.5, ..., 0.6, 0.5, 0.1],
        [0.1, 0.1, 0.1, ..., 1. , 0.7, 0.1],
        [0.1, 0.1, 0.1, ..., 1. , 1. , 0.1],
        ...,
        [0.2, 0.3, 0.2, ..., 0.7, 1. , 0.2],
        [0.1, 0.1, 0.1, ..., 1. , 1. , 0.1],
        [0.1, 0.1, 0.1, ..., 0.7, 0.1, 0.1]]),
 'cancerTargets': array([[1, 1, 1, ..., 0, 0, 1],
        [0, 0, 0, ..., 1, 1, 0]], dtype=uint8)}

# This is a comment

In [69]:
print("the shape of cancerInputs is " + str(data['cancerInputs'].shape) )
print("the shape of cancerTargets is " , data['cancerTargets'].shape )

the shape of cancerInputs is (9, 699)
the shape of cancerTargets is  (2, 699)


In [60]:
X=data['cancerInputs']
X

array([[0.2, 0.2, 0.5, ..., 0.6, 0.5, 0.1],
       [0.1, 0.1, 0.1, ..., 1. , 0.7, 0.1],
       [0.1, 0.1, 0.1, ..., 1. , 1. , 0.1],
       ...,
       [0.2, 0.3, 0.2, ..., 0.7, 1. , 0.2],
       [0.1, 0.1, 0.1, ..., 1. , 1. , 0.1],
       [0.1, 0.1, 0.1, ..., 0.7, 0.1, 0.1]])

In [7]:
X.shape

(9, 699)

In [61]:
y=data['cancerTargets']

In [66]:
y.shape
y[:,0:5]

array([[1, 1, 1, 0, 1],
       [0, 0, 0, 1, 0]], dtype=uint8)

In [67]:
from sklearn.linear_model import LogisticRegression

In [68]:
model = LogisticRegression()

We need to transpose X and y before fitting "model"

In [70]:
XX = np.transpose(X)
yy = np.transpose(y)
yy = yy[:,1]

In [73]:
yy.shape
yy
print(np.mean(yy))

0.3447782546494993


In [81]:
model=LogisticRegression()
model=model.fit(XX,yy)
model.coef_

array([[2.97214277, 1.66988923, 2.06616005, 1.36955229, 0.95933603,
        3.09459596, 2.03103956, 1.4492378 , 1.21773191]])

In [82]:
py_hat = model.predict_proba(XX)

In [83]:
py_hat

array([[9.87993709e-01, 1.20062906e-02],
       [9.85329561e-01, 1.46704390e-02],
       [9.71212465e-01, 2.87875351e-02],
       ...,
       [4.15810993e-04, 9.99584189e-01],
       [1.38931426e-03, 9.98610686e-01],
       [9.91053090e-01, 8.94691003e-03]])

In [85]:
yy_hat = model.predict(XX)
yy_hat

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,

In [86]:
np.mean(yy_hat == yy)

0.9656652360515021

In [87]:
weights = model.coef_

In [36]:
weights

array([[2.97214277, 1.66988923, 2.06616005, 1.36955229, 0.95933603,
        3.09459596, 2.03103956, 1.4492378 , 1.21773191]])

In [88]:
from matplotlib import pyplot as plt

In [89]:
plt.stem(weights[0,:])

<StemContainer object of 3 artists>

In [43]:
weights.shape

(1, 9)